### ISSUE TITLE
Allow users to set coverage threshold

### ISSUE THREAD

**Issue by OmgImAlexis** [lassjs/lass#12]
Since not everyone will want 100% coverage to be required maybe we can add an option to allow the user to select a prefered percentage.

**Comment by AndreasPizsa** [comment]
I actually like the 100% default.

In those rare cases where 100% coverage isn't possible, I exclude untestable lines using 
[`/* istanbul ignore */`](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.mdistaunbul).

Using comments documents the fact that some lines have been excluded from coverage, it is easy to find in the code and still lets you achieve 100% coverage.

**Comment by niftylettuce** [comment]
closing for now, please open PR if you want to get this in
