### ISSUE TITLE
Scoped packaged not using the correct name

### ISSUE THREAD

**Issue by OmgImAlexis** [lassjs/lass#17]
Since the string passed to lass starts with `@` it should prompt to use `@ladjs/email` as the package name not just the directory name.

```
➜  code lass @ladjs/email
> Generating package in /Users/xo/code/@ladjs/email
? What is the name of the new package (email)
```

**Comment by niftylettuce** [comment]
Yeah I had this issue too, but I'm not sure how to pass defaults to `sao`.

Of course we'd have to parse `@` and `/` out, so here's the code to do that and get the `name`:

```
const targetPath = process.env.TARGET_PATH;
let name = targetPath;
if (
  targetPath.charAt(0) === '@' &&
  targetPath.indexOf('/') < targetPath.length - 1
) {
	name = targetPath.substring(targetPath.indexOf('/') + 1);
}
console.log('targetPath', targetPath);
console.log('name', name);
```

Then we'd have to pass name to the template config somehow as a default override?

* https://github.com/lassjs/lass/blob/master/cli.js#L19
* https://github.com/ladjs/lad/blob/master/cli.js#L19

@egoist any idea how to do this? do we need to add a feature to sao or override `template`?

**Comment by egoist** [comment]
Simply change the `default` here: https://github.com/lassjs/lass/blob/0f73c09808585b6c95ec3c0405ca65a0c556ec49/sao.js#L35

**Comment by pablopunk** [comment]
@niftylettuce we can now do this with [*sao*'s `configOptions`](https://github.com/saojs/sao/issues/72#issuecomment-356877395)

**Comment by egoist** [comment]
Maybe we should make the `configOptions` and the `context` argument in `post` hook consistent 😅 and hopefully remove `context` argument in post hook in next major version.

**Comment by pablopunk** [comment]
This was fixed on https://github.com/lassjs/lass/pull/32
