### ISSUE TITLE
Allow for custom prettier / xo settings

### ISSUE THREAD

**Issue by AndreasPizsa** [lassjs/lass#24]
The one thing I need in my code is no semicolons (don’t judge! :-))

So right now the first thing I do after `lass` is to "fix" `package.json` accordingly.

I would like to have personal settings that lass uses. Could be environment variables or a config file in `~`.

I guess that's somehow related to #12

**Comment by OmgImAlexis** [comment]
Since lass is meant for scaffolding it'd make sense to just create your own eslint config and change this PR to allowing a eslint config to be specified when generating the files.

**Comment by AndreasPizsa** [comment]
Exactly. 👍

And then there are several ways to specify this eslint config name: as a command line option, a env var or in a config file.

**Comment by OmgImAlexis** [comment]
Well not really.. the config name needs to be added to your `package.json` so xo can find it.

**Comment by pablopunk** [comment]
Maybe we could choose from a list of popular plugins for xo (standardjs, prettier...) just like when we choose a license from a list of options.

**Comment by OmgImAlexis** [comment]
I'd also suggest allowing a custom option that expects a npm path like `omgimalexis/eslint-config`.

We should also remember the option like we do username, etc. so the user next time can use the same one without needing to change anything.

**Comment by niftylettuce** [comment]
Please use version 0.3.4 now available in NPM.  It provides an option to choose your ESLint configuration (either prettier or standard), and it defaults to prettier.  If you'd like to add more options please submit a PR.  Thanks to @pablopunk for the great work here.
