### ISSUE TITLE
Should we turn off `"check_coverage"` flag by default for nyc in package.json?

### ISSUE THREAD

**Issue by niftylettuce** [lassjs/lass#27]
@OmgImAlexis open to your thoughts - shouldn't we have this set to `false` by default?  it's very hard to achieve 100% in projects without wasting time

**Comment by OmgImAlexis** [comment]
I'd say we should set it to at least 20% or something, we can always tweak it but I want at least enough that it may persuade people to add more tests. Also 20% should cover the tests we ship with.

**Comment by pablopunk** [comment]
I agree with @OmgImAlexis
