### ISSUE TITLE
Add initial git commit

### ISSUE THREAD

**Issue by Spence-S** [lassjs/lass#51]
Add an initial git commit to the project with a commit message like `Initial commit from Lass`

I think it allows more flexibility for a dev to want to change or squash _their_ initial commit/changes without having to go through a bunch of steps. Plus it brands Lass a little more. I think it's still pretty clean in git history.

Thoughts?

**Comment by niftylettuce** [comment]
rockstar

**Comment by niftylettuce** [comment]
I think that's a great idea, maybe `feat: initial commit from https://lass.js.org` so it has a clickable URL and also adheres to commitlint

**Comment by niftylettuce** [comment]
PR welcome!

**Comment by niftylettuce** [comment]
Released as v2.0.8 to npm
