### ISSUE TITLE
remark -qfo not terminated

### ISSUE THREAD

**Issue by smmoosavi** [lassjs/lass#7]
`remark -qfo` not terminated after run `git commit`. I think it should be fixed with change 
 `"*.md": ["remark -qfo", "git add"]` to `"*.md": ["remark . -qfo", "git add"]` in lint-staged

**Comment by niftylettuce** [comment]
agreed, I forgot to do this, one moment

**Comment by niftylettuce** [comment]
`npm install -g lass@0.1.3`
